name: sedutil
version: TAG
target:
  build: earthly +build
  build_provider: earthly
docker:
  build:
    base: kt-build-generic-bullseye:master
  run:
    base: kt-run-generic-bullseye:master
skip_debian: true
skip_docker: true
