name: sedutil
version: TAG
target:
  build: bash ManualBuild.sh
docker:
  build:
    base: kt-build-generic-bullseye:master
  run:
    base: kt-run-generic-bullseye:master
skip_debian: true
skip_docker: true
