name: sedutil
version: TAG
target:
  build: bash ManualBuild.sh && mkdir artifacts && mv *.deb artifacts
  earthly_lib_branch: ing-multi-debs
docker:
  build:
    base: kt-build-generic-bullseye:master
  run:
    base: kt-run-generic-bullseye:master
create_debian: true
package:
  repository: debian-local-ops
  server: ktcontinousdelivery7fbf-ops
  kbt_root_dir: /usr/local/bin
  distribution: all
skip_docker: true
